Feature/service registry improvements
ru-fix/jfix-zookeeper pull request #10
Opened 2020-06-08 11:04 UTC by phoenigm

2020-06-08 13:55 UTC, swarmshine requested changes

2020-06-08 13:55 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistryConfig.kt
> +                expirationPeriod = disconnectTimeout.dividedBy(3),
С такими параметрами по каждому локу ты будешь каждые 10 секунд в zookeeper запись делать. 
Может сделаем  как у PersistentExpiringLockManagerConfig по умолчанию, чтобы раз в минуту в zk писать обновление состояние или хотя бы раз в 30 секунд?

Просто в zk wal лог нехилую нагрузку на iops дает и в него все упирается если записей много таких 
Продление лока и TTL у лока сделаны для того чтобы уж на пол дня он не остался захвачен. То что кто-то в случае аварии 1 минуту не сможет его захватывать думаю по умолчанию нормальная ситуация.

2020-06-08 13:55 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                    logger.error("Lock=$lockIdentity not found")
Если вернули empty должно быть это какоето кривое состояние и надо поадать с большой ошибкой?
У тебя вроде код пойдет дальше и у нас будет NPE?

2020-06-08 13:55 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                if (lockState.expirationTimeStamp.plus(config.get().disconnectTimeout).isBefore(Instant.now())) {
Насколько нужно ServiceIdRegistry  заглядывать и проверять expirationTimestamp, как будто опять проблема с разграничением отвественности между компонентами?
У нас есть PersistentExpiringLockManager который обсужиывает наши локи и поддержиывает их в занятом состоянии. Если случился разрыв связи, а потом восстановление, задача PersistentExpiringLockManager пролонгировать локи, какие смог, и сообщить своему клиенту что какой-то лок потерян и не может быть пролонгирован. Для этого у него есть LockProlongationFailedListener.
Можно построить схему: ServiceInstanceIdRegsitry общается с PersistentExpiringLockManager и получает от него информацию если вдруг какой-то лок потерян. И если мы потеряли - то тут вопрос что нужно делать
Предлагаю: регулярно пытаться захватить лок обратно и ругаться если это не вышло. 
С одной стороны мы получим информирование об ошибке регулярное, с другой стороны самовосстановление.

2020-06-08 14:07 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                    logger.error("Lock=$lockIdentity not found")
По сути можно было падать с illegal state, но тут была идея, чтобы остальные локи хотя бы зареконнектить, которые в пуле

2020-06-08 14:23 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistryConfig.kt
> +                expirationPeriod = disconnectTimeout.dividedBy(3),
сделал раз в 30 сек обновление

2020-06-08 14:25 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                    logger.error("Lock=$lockIdentity not found")
да, тут спик должен был быть

2020-06-08 15:37 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                if (lockState.expirationTimeStamp.plus(config.get().disconnectTimeout).isBefore(Instant.now())) {
Обновленная модель:

-  при реконнекте пытаемся захватить лок по новой, если не вышло, то логируем ошибки.

- если каким-то образом service regisrty завершился форсом, то локи на id останутся в зк и не будут использоваться последующими зарегистрированными сервисаи

2020-06-09 07:02 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +                    logger.error("Lock=$lockIdentity not found")
кусок кода удален теперь этот

2020-06-10 07:26 UTC, phoenigm commented
По текущей модели:

- При register() захватывается лок  на выданный instance id на указанное в конфигах время.
- Если лок этого инстанса заэкспайрился, то этот инстанс считается мертвым и его instance id могут занять новые регистрирующиеся сервисы.
- Если внезапно возникла ситуация, что этот инстанс переподключился после того, как его лок заэкспайрился, а его instance id занял другой сервис, то с периодичностью lockProlongationInterval будут писаться сообщения об ошибке. Данная ситуация исправляется выключением переподлкюченного инстанса.
Тест на вышеописанный сченарий: `ServiceInstanceIdRegistryConnectionProblemsTest.'client disconnected, instance id's lock expired, register instance on expired instance id, client of expired lock reconnected with error'`

2020-06-10 15:51 UTC, swarmshine requested changes

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
> +        return curatorFramework.getChildren()
Why you are breaking encapsulation boundaries? 
I think it would be better that ONLY PersistenExpiringDistributedLock class knows about INTERNAL representation of the lock. 
```
    enum NodeState {EXPIRED_LOCK, NOT_EXPIRED_LOCK, NODE_ABSENT, NOT_A_LOCK}
    public static NodeState readLockNodeState(String path){
        //load lock state from zookeeper,
        //check that this is a lock
        //and return lock's state
       //or empty if there is no lock there
    }
```

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
> +                .stream()
Who knows that under `serviceRegistrationPath` path should be registered list of locks that impersonate service registered id?  - The only one guy:  ServiceInstanceIdRegistry! So
```
//in ServiceInstanceIdRegistry class
private fun getNonExpiredLockNodesInPath(path:  String): List<String> {
  ...
   val existenLockState = PersistenExpiringDistributedLock.readLockState(path + lockName)
  ...
   
}
``

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
Why you are using logarithmic SkipList instead of constant ConcurrentHashMap.newKeySet?

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
>          throw Exception("Failed to register service=$serviceName.")
Could you please add to cause the last exception from last attempt?

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
>      }
Why you are hiding exception in close Method in catch section?
```
logger.error("Error during instance id registry close.")<- missing exception object in log
```

2020-06-10 15:51 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +            if (lockManager.tryAcquire(lockIdentity) {
Рассмотрим ситуацию:
1. ЛокМенеджер захватил лок-1  на 1 час
2. Случился разрыв связи на 5 секунд
3. Сработал event и вызвался reconnect
4. вызывается lockManager.tryAcquire(lockIdentity)
    он пытается создать новый PersistentExpiringDistributedLock
    но старый еще жив и время его жизни не истекло
    lockManager.tryAcquire(lockIdentity) вернет false 
5. Мы напишем что все плохо и что    `lock of this instance was expired and new service was registered`
    хотя на самом деле наш лок вполне живой и здоровый. 

- Предлагаю в ServiceInstanceIdRegistry добавить тест на этот случай. 
- Впречатленеи что ServiceInstanceIdRegistry не должен слушать reconnect, он должен слушать только LockProlongationFailedListener, и если он сработал, значит лок потерян и его надо после этого пытаться регулярно захватить  lockManager.tryAcquire, и если не получилось то кричать.

2020-06-10 17:43 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
replaced

2020-06-10 17:43 UTC, phoenigm commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
> +                .stream()
fixed

2020-06-10 17:43 UTC, phoenigm commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
> +        return curatorFramework.getChildren()
fixed

2020-06-11 07:30 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
>          throw Exception("Failed to register service=$serviceName.")
log extended

2020-06-11 07:31 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
>      }
fixed

2020-06-11 08:00 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +            if (lockManager.tryAcquire(lockIdentity) {
действительно, реконнект убрал, тест добавил

2020-06-12 09:49 UTC, swarmshine requested changes

2020-06-12 09:49 UTC, swarmshine commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringDistributedLock.java
> +    public static LockNodeState readLockNodeState(CuratorFramework curator, String path) {
Could you please add test for new method in PersistentExpiringDistributedLockTest?

2020-06-12 09:49 UTC, swarmshine commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
>              locks.remove(lockId);
you are removing same lockId twice: at the start and at the end in finally, why is that?

2020-06-12 09:49 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +            val alreadyRegisteredInstanceIds = getNonExpiredLockNodesInPath()
Сейчас API
`ServiceInstanceIdRegistry#register(serviceName: String): String`
выглядит так что можно предположить следующее:
- Реестр регистрирует экзепляры конкретного сервиса
- Каждому экземпляру выдется id 
- Так как при регистрации передается имя очень похоже что для одного и того же имени ведется свой учет выданных id, то есть если мы зарегистрируем 3 сервиса A и 2  сервиса B то получим следующие id:
A1, A2, A3, B1, B2

Фактически же код работает по другому, он просто игнорирует имя сервиса. 
То есть если я хочу получить сценарий работы A1, A2, A3, B1, B2 то я должен сделать 
```
val serviceInstanceIdRegistryForA = ServiceInstanceIdRegistry(...)
val serviceInstanceIdRegistryForB = ServiceInstanceIdRegistry(...)
```
что противоречит тому как организованы методы API и их документация. 

Предлагаю:
А) либо оставить текущее API и сделать чтобы регистрация шла в виде A1, A2, A3, B1, B2
  для этого можно просто использовать поддерево serviceRegistrationPath/serviceName/id
Б) Либо поправить API, выкинуть имя сервиса из registry метода и перенести имя сервиса в конструктор для того чтобы его внутрь meta лока записывать для отладки и в документации указать что елси хотите 
A1, A2, A3, B1, B2 то делайте несколько экземпляров этого класса. 

Мне нравится вариант A так как для разных типов сервисов мы переиспользуем одни и те же служебные потоки и один LockManager

2020-06-12 09:49 UTC, swarmshine commented on jfix-zookeeper/src/test/kotlin/ru/fix/zookeeper/instance/registry/AbstractServiceInstanceIdRegistryTest.kt
>      protected fun isInstanceIdLockExpired(instanceId: String, disconnectTimeout: Duration): Boolean {
Почему вдруг тест на ServiceInstanceIdRegistry вдруг знает про внутреннее представление лока?
Тест хоть  и тест но он тоже должен придерживаться разграничения отвественности и инкапсуляции. 
PersistentExpiringDistributedLock.readLockNodeState тут не достаточен?

И сразу стоит проверить а действительно ли в тесте на ServiceInstanceRegistry нам нужно заглядывать в его лок. То есть конечно местами это нужно сделать чтобы
- А) например сделать тест в котором мы проверяем что ServiceInstanceRegistry работает с использованеим лока,  создает его и затем удаляет когда мы делаем unregister("app") или закрываем ServiceInstanceRegistry
- Б) чтобы дождаться наступления какого-то состояния, например мы хотим доджаться что лок стухнет, а для этого нам надо его состояние почекать

При этом всегда стоит в тесте показывать какое поведенеи от нашего serviceRegistry увидит клиент. 
Например:

`prolongation of instance id's lock works fine after reconnect`
Если тут речь о том что в случае потери соединения на короткое время мы не теряем занятость идентификатора сервиса то 
```
registry = new Registry(MinFreeGen())
registry.register("app").shouldBe("1")
netCrusher.close()
state = zkServer.startWatchClientState()
await(state == LOSS)
netCrusher.open()
registry.register("app").shouldBe(2)
```

Если тут речь о том что в случае потери соединения на короткое время другой реестр не должен захватить занятые идентификаторые  приложением которое потеряло свзять то

```
registry1 = new Registry(netCrushedProxy, MinFreeGen())
registry2 = new Registry(directZkConnect, MinFreeGen())

registry1.register("app").shouldBe("1")
netCrusher.close()
state = zkServer.startWatchClientState()
await(state == LOSS)

registry2.register("app").shouldBe("2")

netCrusher.open()
registry.register("app").shouldBe(3)
```
Ведь при MinFree ты знаешь в какой последовательности должны быть выданы ID 
И если они выданы правильно значит  ServiceIdRegistry соблюдает контракт и "для пользователя" он работает корректно. 

То есть мы проверяем что эта штука 
- не дает нам выдать одинаковые iD при разного рода проблемах
- уведомляет нас если мы потеряли регистрацию, например  в логе
и т.п. 

Предлагаю пересмотреть тест кейсы и там где мы можем проверить поведение именно со стороны клиента - реализовать такие кейсы или добавить. 

При этом повторюс ты конечно можешь проверять что по заданному пути есть лок, и что он не протух что ServiceInstanceIdRegisry корректно пишет что-то в ZooKeeper, например,  по ранее указанным причинам.
Но нужно явно показать в тесте что контракт поведения для клиента соблюдается.

2020-06-12 09:49 UTC, swarmshine commented on jfix-zookeeper/src/test/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistryTest.kt
> +        createInstanceIdRegistry(lockAcquirePeriod = lockAcquirePeriod).register("abs-rate")
Полагаю нам нужен тест: 
Взяли id у реестра. 
Пропало соединение. 
Лок протух.
Другой Registry2 захватил лок.
Registry1 при этом  регулярно пытается захватить  новый лок на свой id для которого он потерял лок. и если у него не будет получаться он будет кричать в лог ошибкой.
Registry2 закрываем - то есть мы выключаем второй сервер.
У Registry1 получается наконец то новый лок  захватить для свого id он успокоится и перестанет писать ошибку. 

То есть кейс

2020-06-15 04:25 UTC, phoenigm commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringLockManager.java
>              locks.remove(lockId);
removed in finally

2020-06-15 04:25 UTC, phoenigm commented on jfix-zookeeper/src/main/java/ru/fix/zookeeper/lock/PersistentExpiringDistributedLock.java
> +    public static LockNodeState readLockNodeState(CuratorFramework curator, String path) {
added

2020-06-16 13:28 UTC, phoenigm commented on jfix-zookeeper/src/test/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistryTest.kt
> +        createInstanceIdRegistry(lockAcquirePeriod = lockAcquirePeriod).register("abs-rate")
добавил

2020-06-16 13:31 UTC, phoenigm commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +            val alreadyRegisteredInstanceIds = getNonExpiredLockNodesInPath()
выбрал вариант 2 и добавил метод `unregister(serviceName, id)`

2020-06-16 14:07 UTC, phoenigm commented
По тест кейсам, где присутсвует потеря соеднинения:
-  Registry зарегистрировал инстанс, потерялось соединение, но лок не протух, и после восстановления соединения registry сможет пролонгировать лок инстанса.
- Registry зарегистрировал инстанс, потерялось соединение, лок не протух. Новый инстанс с тем же serviceName получит новый еще незанятый instacneId.
- Registry зарегистрировал инстанс, потерялось соединение, лок протух. Новый инстанс с тем же serviceName получит instanceId, чей лок уже протух.
- Registry зарегистрировал инстанс, потерялось соединение, лок протух. Второй registry регистрирует  новый инстанс, выдается instanceId протухшего лока. Интстанс, у которого заняли instanceId, восстаналивает соединение и начинает кидать ошибки, потому что не может пролонгировать не свой лок на instanceId. Если сделать graceful shutdown через close() у первого registry, то ошибки перестают появляться в логах. При этому другой resitry также продолжает контролировать instanceId и пролонигировать его лок.
- Такой же кейс как и выше, но только проблема решается выключение второго registry.
- Лок инстанса не тухнет при моментном моргании сети.
- Все локи инстансов под управлением одного registry протухли после потери соединения и все смогли запролонгировать локи после восстановления соединения.

2020-06-16 14:10 UTC, phoenigm commented on jfix-zookeeper/src/test/kotlin/ru/fix/zookeeper/instance/registry/AbstractServiceInstanceIdRegistryTest.kt
>      protected fun isInstanceIdLockExpired(instanceId: String, disconnectTimeout: Duration): Boolean {
теперь проверка протухшего лока через PersistentExpiringDistributedLock.readLockNodeState

2020-06-16 15:06 UTC, swarmshine commented on jfix-zookeeper/src/main/kotlin/ru/fix/zookeeper/instance/registry/ServiceInstanceIdRegistry.kt
> +            val alreadyRegisteredInstanceIds = getNonExpiredLockNodesInPath()
в варианте Б не нужен в register методе имя сервиса передавать, не понятно зачем оно там?

2020-06-17 05:34 UTC, swarmshine requested changes
- prolongationFallback called only once, we probably should add scheduler into registry,so it will continue to retry to acquire lock back.

2020-06-17 13:48 UTC, merged